sudo: required

language: python

services:
- docker

script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_script:
- export DOCKER_REPO=pocketsquare/pocket-square-sort-shuffle
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO

env:
  global:
  - secure: QSTQqvT5Qo7stk6qe8FEiTTggIrLcXs8TZ2/0+x1NGHw1aaZZ4izHouqtuoHtF/EO759jyMUJGHIUI3PlKOsv1MsMwUBMlwuQ0XoZCtyks3YCLZH2WMpN1osrHmxj8I77KqhhWlhy8HSo+f2MxBnnA6LTmyivCg2hPO0AaEFwJdNSSASb4UMoRd/zXRVqiG9cguBeSf6fn/g8JNpH5kOFaZQK+heX/YosErWFkAV5LRbb65Pexp4kK3QhD7fR1TIR4VJ3Ab8JglAffqSIAaKjRFCQdtDDkM87D7vrWSgIATZilwRj+emrt8P03vJiGQ0Tv98Jcv8LzvOKPbFmPJgLNfSov90LJRYXRFw8aeUf2ln/Ug2jO6Qy93Tmv3QpkOsSO0BQRzHX+TaHbZodYXldVO+xGGfIQ/BEdaaMCuun5PV1eDC+wgwsNMgXWg8Btc9o0vOLfVr68ukucB+0diAh3PFFsFOrjxII3Jep+Tlo7CBVuQRmZpVQsIi3fsFfzJGpKrey/gAhtbPsXW7kfLvndANyCrjpEuf0UsW6btwtcPpQ5J5q2TNt2Mkyo9TFCS8rhyI9eVl0vQr0hSOT8FHBtHg/azJkn61eRIijuXyXX2T/zvpryqUU6lYL/QCwpVsdpIs68J4qx5fT/QnP6AzJa3HShm/mNMvN+Ubw0/DlsA=
  - secure: YN6cD5bVjzHURNeBS3SYck7Y755z/vZhRT7CHghUNm4XiyhFOZlJUJmECu50oIwS6tXoNwScbhCFqHb2MRwWoXEq765AnaFwVuiSfC3KU5vQZf9Xivk3Gtm9vgm27cSFU/Uci7eWaggq4VLhCmXXSrjfpbi6BWvG0/N5blxlEfqZqMuTHmVUzV0XM65ler5QFYN/286ZR6gIvhUL8hT4+k6VhaaGDLgM6Cf/uwmaHlaIH3Z+8DrSQxfmi1Ix3sTcqaGD6y3pJC4HS1lVMKD7umNcHxwwndPKqpb9WfUVCe8fYImaCgoD+qbfWCI8nyjZVNnCvuwQmNa1ORhXQBWZsaluXkqWuWU2ngNsXs20i8DVOFtidIJkKfFQVYwjg9PIEi8GIkPystmqYHAmL6RYK++zMrvLzisqdsLSxvd5rytszhCv94yDUpqySLKxk5Au9kEpclINHTIkJArTl/hUmTPRMWKJaBos/VOSq9R3Vio8qOHvqKKlIQ77rgufqaNg39MuzOh8wlnZwPXqbzwwHCt1kHjp6wrfO0g+v765d+BPaEV2ZUno0OCpxVQZcdgfmrHNdkDCGnBWc6nz9OD23XJQTgxLc8PTF1XGU2mVGOcJ0E0MPnPHloH+WKMxLZ3UySFZJyUi+wfiupAciEYE7Z61sNSnFIrJgiFltchuxNg=
  - secure: ZB01wSChPEcJJNd8sZ9OXyLqHWmnefciuYD2dY7dfieXKlLHuaFcJgWjTl/26fu6LpKBMOY9yM37uZ4v12tDF7k3B1GWc8dRGHxVzy5fEg1ElmO4+HqinyWiKsbs7oYPDh7YSD2F5Hen064ZvmFjm6ZmpFOQkp4nUD+lns18PxU3QNWFZe9d0k7oGkDO8IMkkR1SzBHq0rnT7SWxAo2K31WOezXbDRROaeW9Ljwit72C2Ria+hvEgXWWwe7+MBf9N3Ak6InnVEeBu866mLJa5FN4afDEwe7/ce5fPIiW3FaqEjrImwFm/8VO2YECb7cdEm/GwO45eG1c40wLWGPQ4sNChRTDPz4funntG+7SuntT0Lr4Jmu1NFKPzKXOB6iwUiWqBxjmICPg5AGQFlckCnSKYyMEKj2EkFR3BDP5A+jy/pM+FAkziuoMcLolFQZpH0TXRcEo1fcalfNXSJd66vx9OZemWThwcIUJAd6oTZg9g5hfOGDoXs7o9L4F2JPrhcLxq6uiSwgdwNHustgqdHpo8DFcCJAp7BeQfZXaj2GGz1zOMQkas4BacbWybaejvu5JgG7CAUVuoXsj0re+3kEJ8ifZ6yNhceXGzqEDGRcWJn6WpMAdWpWRLbJj+SqLrRHEECG0+PoqsFrcM8RGUVCAOFOh8wx83TZaLx/Ljyg=
