sudo: required

language: python

services:
- docker

script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_script:
- export DOCKER_REPO=pocketsquare/pocket-square-sort-shuffle
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO

env:
  global:
  - secure: q0EWzHjT7V4Z4TEn9GedOv7aomZhwZWYRQrxlGNQO2yEO/UqKHDBtsi9venGoJfYbdwiWCLCK0iKV/fJaawLE3QyJbUmm5GaJuNa6x8OdEfo3enBnWAKT8VLCVTnyDKqDE/Sd8EksTZ3zaDC8f4NWBLVcH+NMkXnzhGJECIiGOtnsa5e42FjzLNwX7xnUGUDWJhBVbK3gtlsKuImVYluUahlsZiIiqWUfgJrCK11tCdLVXXWHsvyA7wfmiSoDvuhByaOCrvDrVA+5x4npyAju25PQtFkNIbQ3erTkA5gFKEiwRavlSAIsWN6MoyYwjGX1iQd3CbmHe6YlZLTEln4oeN5Hl9g6IZH0X6FYmXm6mBRRSAR+EU058/LA4Xuji2+NIU0rZY09EWN5Xs21uYMN0MRXcPGKnZkJnzVJYd3fSACVaS9AbySEY9zjzwnijhmwcFoCP5UD+UjfVSoBRLaJmXUyNU6i7DHHzYqOLotSqhS+181go1P/ISY+d4Zbmma/PZh/y4z6Pk/6otS1gdkmkdffPvAk5yT4wswFwxDl9mwdXZ9uZgWWBwr1aYjkQQlOXQeZQPJY6lLP/cKZsYuFJqEiq27BKXk264w+K1yw3r/P4RNfBOa/8L00FsoMXMapNLCNzAcjJ72fss/1OFtXcWjJHqBox9UJwSX8xwWQos=
  - secure: tGIp1xFeqXmg66dzY0vDsYziDcmz7FEZDWiSHX/ZI3mo9+W/pPc4HNrjjMNEYJSykHIPbtH3iW1oscRNN/XtT4+IXCuYuqAsVV/K7GHMxM5si13YsnTUuvstSu6UobS4OI78AkAT7aNg/7UOguN/EjJNmOIolxVwqBUBYGr+Qg2p1k9/UOsYXI3TYJpSGTd7py+pBaHUdPxFPesJs49UOSDkbE+uHZ+CoQG851uiyhITNr/rvMZUkzzhO/5noD/5O5d6nnHIWQKGMs4l46DuYP9hT0AS4yOxzMKO6dWrWnK3ifx014VYJvfBKOLqjVtwbqOFyzStN7waRIsHKDUTwWWiT+PABc9BaxgF2W5Gz0EtriE+FzBCd10bsnxP32Dj5nrq5hzMpGGrxaYnPAanA3irjYoq5/VN3APo+jkbWAx7frARnn2vfeoi33zAbkh0YNuKuB9MjQew4YhRsM6bDZzZzTXI5fATrUZgEjHvJh6mCN5xcgSDQY3kbpAKrJSERhX1vMjWAIa5RWH30Xc8ieWWjuXlZhAMFnUHsx3s7kx6fvBuFND+j9dVihYNRy1vroHNPM5uFJLzdfqsnpS2v/9EyoB3pco3G+0Lz7FoPOEVyHOgbK3Nlz4kr7SvvizRqmMNSoyuPjZsGlRyIkLMj6xWpUxjWRIQ1qIhnjHHkQc=
  - secure: W8tsf98rELH4dQSS7JRbf/AHVGJSsUdMVsnDP371l9gyT2Bsl+8rCXxKeqkHKKHqb6PmL44spA0IeFs1SvGoj3Io5b4U6Gi6fIc1OkyJQ8VrvUJvuRpTDWRljzQSgEzmUHxWackKl0s7DcrCl5k1bOfMcdTE67KUDulALZRGuSpoKI3EYYD0vQ/X/ntDmAiVxdAV3WHqzdpPpTgdDWFsbLk20OiJ0+49QNnwwb5N49FKdA5DSVuJ5Qs5Ylfwx5/ZIiulSwn2Ot1AqnE36/p00tRcaNTq2Q/0vNP9Dh75/cqKeccY/PsuXQqjzPrd/8da4BQtnLHypVefd+owMpAjpJu++E68erwr8zTyFybRaeaN+G0zufJewZAbLJNxzzagGqgBjF160yl8FT4BHCQ3NgeRvVyRNLxPSrn5NzK0+KwK28aA97HkfnlbDDBIoBSujp3dwTutoRR73aGFFK4AJU4t+Eo8xBgBbQnInFELdrO3MyXVU7SDPYXo3OWygtcWuErYo+N9c9FfQZ4nWuEZPpIwumtNOGOj2h7gngxmbuflUPsCHCScqNRhWWlR/MQ0lMyENv9anKRdAyAgbG90YQVEVl02C3o/ZAhB2I/4IX8bXv6hJ2KAx9qiQdF0ZtnrY4iIsvoWKs5xXkY+zqVMdKR1FVF8aEt7rWs9Ux5FrKc=
